// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./src/components/ArticleItem.vue')['default']
    ArticleScrollPage: typeof import('./src/components/common/ArticleScrollPage.vue')['default']
    BaseFooter: typeof import('./src/components/common/BaseFooter.vue')['default']
    BaseHeader: typeof import('./src/components/common/BaseHeader.vue')['default']
    CardArchive: typeof import('./src/components/card/CardArchive.vue')['default']
    CardArticle: typeof import('./src/components/card/CardArticle.vue')['default']
    CardMe: typeof import('./src/components/card/CardMe.vue')['default']
    CardTag: typeof import('./src/components/card/CardTag.vue')['default']
    CommentItem: typeof import('./src/components/comment/CommentItem.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubmenu: typeof import('element-plus/es')['ElSubmenu']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    GoTop: typeof import('./src/components/GoTop.vue')['default']
    MarkdownEditor: typeof import('./src/components/markdown/MarkdownEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scrollpage: typeof import('./src/components/scrollpage/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
